#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander'),
    constants = require( './lib/controllers/constants' );



program
  .version('0.0.1')
  .option('-t, --timer', 'affiche le temps de chargement pour chaque étapes')
  .parse(process.argv);

require('./lib/routes')(program);
