#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander'),
    constants = require( './lib/controllers/constants' );



program
  .version('0.0.1')
  .option('--json', 'generate json report')
  .option('--jpg', 'generate jpg graph')
  .option('--png', 'generate png graph')
  .option('--svg', 'generate svg graph')
  .option('--dot', 'generate dot graph')
  .parse(process.argv);

require('./lib/generateGraph')(program);
